### ISSUE TITLE
Tags and genres not being applied

### ISSUE THREAD

**Issue by Egoistically** [Snd-R/komf#13]
Hello, when using it everything works great, but genres and tags do not stay.
I do not know if this is its intended behavior. What made me open this issue is that, when metadata is being applied (by manually identifying, for example) I can see tags and genres being applied for a split second in the background, but are then removed.
Either way, this is mere curiosity in case something's wrong on my end.
Thank you very much for your amazing work, it truly is a blessing.

**Comment by Snd-R** [comment]
This shouldn't happen.
What metadata providers are you using? Can you provide your config?

**Comment by Snd-R** [comment]
One thing that might be happening is that if you have metadata in files (for example comicInfo file in your cbz) then komf might be overriding it to empty values if provider has no tags

**Comment by Snd-R** [comment]
I've released a fix to an issue that I described above.
Now it shouldn't override any values that has been set in komga if there is no data for that field
See if that works for you now
https://github.com/Snd-R/komf/releases/tag/0.10.1

**Comment by Egoistically** [comment]
Hello, sorry for the late response, I've been really busy.

I have downloaded the latest update and the same thing is still happening, here you have a gif of what I meant, hopefully makes it more clear: https://i.imgur.com/xSRwi8N.gif.
And the frame of the gif where tags do show up: https://i.imgur.com/FWPFi5n.png. They seem to match with the ones it should be fetching.

Here you have my config:
```yaml
komga:
  baseUri: env:KOMF_KOMGA_BASE_URI #or env:KOMF_KOMGA_BASE_URI
  komgaUser: env:KOMF_KOMGA_USER #or env:KOMF_KOMGA_USER
  komgaPassword: env:KOMF_KOMGA_PASSWORD #or env:KOMF_KOMGA_PASSWORD
  eventListener:
    enabled: true
    libraries: [ ]  #listen to all events if empty
  metadataUpdate:
    bookThumbnails: false #update book thumbnails
    seriesThumbnails: false #update series thumbnails
    seriesTitle: true #update series title
    readingDirectionValue: LEFT_TO_RIGHT #override reading direction for all series. should be one of these: LEFT_TO_RIGHT, RIGHT_TO_LEFT, VERTICAL, WEBTOON
  aggregateMetadata: false #if enabled will search and aggregate metadata from all configured providers
discord:
  webhooks: #list of discord webhook urls. Will call these webhooks after series or books were added
  templatesDirectory: "./" #path to a directory with discordWebhook.vm template
database:
  file: ./database.sqlite #database file location.
metadataProviders:
  mangaUpdates:
    priority: 10
    enabled: false
  mal: #requires clientId. See https://myanimelist.net/forum/?topicid=1973077
    clientId: ""
    priority: 20
    enabled: false
  nautiljon:
    priority: 30
    enabled: false
    useOriginalPublisher: true # use original publisher and release dates for series and volumes. If false will use french publisher
    originalPublisherTag:  #if present will add additional tag with specified name ({tagname}: publisherName)
    frenchPublisherTag:  #if present will add additional tag with specified name ({tagname}: publisherName)
  aniList:
    priority: 40
    enabled: true
  yenPress:
    priority: 50
    enabled: false
  kodansha:
    priority: 60
    enabled: false
server:
  port: 8085 #or env:KOMF_SERVER_PORT
logLevel: env:KOMF_LOG_LEVEL #or env:KOMF_LOG_LEVEL
```
Same thing happened with mangaUpdates, also tried enabling aggregateMetadata to no avail.

If you need more details or prefer discussing this on Discord, let me know.
And again, thank you very very much for your hard work, hope you have a nice day.

**Comment by Snd-R** [comment]
The issue was with reading direction override. On update it sent null values in payload for tags and genres which set those fields to empty
With new release reading direction override will happen during main update request alongside with other metadata values
https://github.com/Snd-R/komf/releases/tag/0.10.3

**Comment by Egoistically** [comment]
Works great, for real I cannot thank you enough.
