### ISSUE TITLE
Discord notification not sending after auto/manual scan

### ISSUE THREAD

**Issue by applesoff** [Snd-R/komf#79]
I have tried updating a few series with new books and komf completes everything, adds comicinfo, but at the end when it normally sends a discord notification it now no longer does.
I assume this is due to my updating to komga v1.0.0, now 1.1.0
Any idea if this is something in the yml i need to fix or is this a program issue?

**Comment by Snd-R** [comment]
Komga API changed and removed a field that komf expected in library response
https://github.com/gotson/komga/commit/63e3e7a8ac9e355adb442caef6228417243c0d2d#diff-c5786243342b760b7575b76d8e8a06f4338cdcfe2badd61dbc98763bedc907f9L21

Fixed in [0.30.2](https://github.com/Snd-R/komf/releases/tag/0.30.2)

**Comment by applesoff** [comment]
I am still not receiving notification updates after komf finishes adding metadata.
